version: '3.7'

services:
  neo4j:
    image: neo4j:5.18.1-community
    ports:
      - "7474:7474" # พอร์ตสำหรับเว็บ UI
      - "7687:7687" # พอร์ตสำหรับการเชื่อมต่อ Bolt
    volumes:
      - ./data:/data # โฟลเดอร์เก็บข้อมูล
      # - ./logs:/logs
    environment:
      NEO4J_AUTH: neo4j/Nui4711jeep # ข้อมูลการเข้าสู่ระบบ
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 5G
      NEO4J_dbms_memory_heap_max__size: 5G
    restart: always